org.slf4j.simpleLogger.defaultLogLevel=warn
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.log.io.netty.resolver.dns=error
org.slf4j.simpleLogger.log.redis.clients.jedis.mcf.HealthCheckImpl=error
org.slf4j.simpleLogger.log.io.lettuce.core.failover=off
